# Site settings
title: HS Hackers NYC
location: New York City
description: "Welcome to the High School Hackers NYC meetup group!"
baseurl: ""
url: "http://nyc.hshackers.org"
accent: "#E74C3C"

# Build settings
markdown: kramdown
permalink: pretty
