# Site settings
title: Domínio Público
location: Brasil
description: "Bem vindo ao projeto Domínio Público!"
baseurl: "http://www.dominiopublico.xyz"
url: "http://www.dominiobpublico.xyz"
lang: pt-BR

# More settings
accent: "#E74C3C"
twitter: "DominioXyz"
github: "agnoldo/dompub"
contact: "agnoldo at gmail dot com"
organizers: "Arnaldo Gomes"

# Get Meetup Notifications, visible or hidden
notifications: "visible"

# Get Meetup Notifications, IFTTT recipie URLs
email: "https://ifttt.com/recipes/186850-hs-hackers-nyc-e-mail-notifications"
gcal: "https://ifttt.com/recipes/186851-google-calendar-for-hs-hackers-nyc"
sms: ""
android: ""
ifttt: "http://ifttt.com/"

# Local Meetup Links
meetup1: "The Young Hackers"
meetup1-url: "http://younghackers.us/"
meetup2: "NYC TechBreakfast"
meetup2-url: "http://www.meetup.com/NYC-TechBreakfast/"
meetup3: "NY Tech Meetup"
meetup3-url: "http://www.meetup.com/ny-tech/"

# Build settings
markdown: kramdown
permalink: pretty
